version: '3'
services:
  database:
    image: "postgres"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - go_multi_choice:/var/lib/postgresql/data/
      # - go_multi_choice_test:/var/lib/postgresql/data/


volumes:
  go_multi_choice:
  # go_multi_choice_test:
